name: Ignition ros2 control CI

on:
  pull_request:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: osrf/ros:foxy-desktop
    steps:
    - uses: actions/checkout@v2
    - name: Setup colcon workspace
      id: configure
      run: |
        apt update -qq
        apt install -qq -y lsb-release wget
        cd ..
        mkdir -p /home/ros2_ws/src
        cp -r ign_ros2_control /home/ros2_ws/src/
        sh -c 'echo "deb http://packages.osrfoundation.org/gazebo/ubuntu-stable `lsb_release -cs` main" > /etc/apt/sources.list.d/gazebo-stable.list'
        wget https://packages.osrfoundation.org/gazebo.key -O - | apt-key add -
        IGN_DEPS="libignition-gazebo5-dev libignition-plugin1-dev libignition-physics4-dev"
        apt-get update && apt-get upgrade -q -y
        apt-get update && apt-get install -q -y --no-install-recommends \
          dirmngr \
          gnupg2 \
          lsb-release \
          python3-colcon-ros \
          $IGN_DEPS
        cd /home/ros2_ws/src/
        rosdep update
        rosdep install --from-paths ./ -i -y --rosdistro foxy \
          --ignore-src
    - name: Build project
      id: build
      run: |
        cd /home/ros2_ws/
        . /opt/ros/foxy/local_setup.sh
        colcon build --packages-up-to ignition_ros2_control_demos
    - name: Run tests
      id: test
      run: |
        cd /home/ros2_ws/
        . /opt/ros/foxy/local_setup.sh
        colcon test --event-handlers console_direct+ --packages-select ignition_ros2_control ignition_ros2_control_demos
        colcon test-result
